name: terraform-fmt-check

on: [push]

jobs:
  terraform-fmt-check:
    runs-on: ubuntu-latest
    name: terraform-fmt-check
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v2
        id: fmt-check
        with:
          path: terraform
